// Code generated by protoc-gen-go. DO NOT EDIT.
// source: connect.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	connect.proto
	create_federate_execution.proto
	services.proto
	test.proto
	types.proto

It has these top-level messages:
	ConnectRequest
	ConnectResponse
	CreateFederateExecutionRequest
	CreateFederateExecutionResponse
	HLAHandle
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Ignoring public import of HLAHandle from types.proto

type CallbackModel int32

const (
	CallbackModel_IMMEDIATE CallbackModel = 0
	CallbackModel_EVOKED    CallbackModel = 1
)

var CallbackModel_name = map[int32]string{
	0: "IMMEDIATE",
	1: "EVOKED",
}
var CallbackModel_value = map[string]int32{
	"IMMEDIATE": 0,
	"EVOKED":    1,
}

func (x CallbackModel) String() string {
	return proto.EnumName(CallbackModel_name, int32(x))
}
func (CallbackModel) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ConnectResponse_ConnectResult int32

const (
	ConnectResponse_SUCCESS                           ConnectResponse_ConnectResult = 0
	ConnectResponse_CONNECTION_FAILED                 ConnectResponse_ConnectResult = 1
	ConnectResponse_UNSUPPORTED_CALLBACK_MODEL        ConnectResponse_ConnectResult = 2
	ConnectResponse_INVALID_LOCAL_SETTINGS_DESIGNATOR ConnectResponse_ConnectResult = 3
	ConnectResponse_ALREADY_CONNECTED                 ConnectResponse_ConnectResult = 4
	ConnectResponse_RTI_INTERNAL_ERROR                ConnectResponse_ConnectResult = 5
)

var ConnectResponse_ConnectResult_name = map[int32]string{
	0: "SUCCESS",
	1: "CONNECTION_FAILED",
	2: "UNSUPPORTED_CALLBACK_MODEL",
	3: "INVALID_LOCAL_SETTINGS_DESIGNATOR",
	4: "ALREADY_CONNECTED",
	5: "RTI_INTERNAL_ERROR",
}
var ConnectResponse_ConnectResult_value = map[string]int32{
	"SUCCESS":                           0,
	"CONNECTION_FAILED":                 1,
	"UNSUPPORTED_CALLBACK_MODEL":        2,
	"INVALID_LOCAL_SETTINGS_DESIGNATOR": 3,
	"ALREADY_CONNECTED":                 4,
	"RTI_INTERNAL_ERROR":                5,
}

func (x ConnectResponse_ConnectResult) String() string {
	return proto.EnumName(ConnectResponse_ConnectResult_name, int32(x))
}
func (ConnectResponse_ConnectResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

type ConnectRequest struct {
	CallbackModel CallbackModel `protobuf:"varint,1,opt,name=callback_model,json=callbackModel,enum=api.CallbackModel" json:"callback_model,omitempty"`
	LocalSettings string        `protobuf:"bytes,2,opt,name=local_settings,json=localSettings" json:"local_settings,omitempty"`
}

func (m *ConnectRequest) Reset()                    { *m = ConnectRequest{} }
func (m *ConnectRequest) String() string            { return proto.CompactTextString(m) }
func (*ConnectRequest) ProtoMessage()               {}
func (*ConnectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ConnectRequest) GetCallbackModel() CallbackModel {
	if m != nil {
		return m.CallbackModel
	}
	return CallbackModel_IMMEDIATE
}

func (m *ConnectRequest) GetLocalSettings() string {
	if m != nil {
		return m.LocalSettings
	}
	return ""
}

type ConnectResponse struct {
	Result ConnectResponse_ConnectResult `protobuf:"varint,1,opt,name=result,enum=api.ConnectResponse_ConnectResult" json:"result,omitempty"`
}

func (m *ConnectResponse) Reset()                    { *m = ConnectResponse{} }
func (m *ConnectResponse) String() string            { return proto.CompactTextString(m) }
func (*ConnectResponse) ProtoMessage()               {}
func (*ConnectResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ConnectResponse) GetResult() ConnectResponse_ConnectResult {
	if m != nil {
		return m.Result
	}
	return ConnectResponse_SUCCESS
}

func init() {
	proto.RegisterType((*ConnectRequest)(nil), "api.ConnectRequest")
	proto.RegisterType((*ConnectResponse)(nil), "api.ConnectResponse")
	proto.RegisterEnum("api.CallbackModel", CallbackModel_name, CallbackModel_value)
	proto.RegisterEnum("api.ConnectResponse_ConnectResult", ConnectResponse_ConnectResult_name, ConnectResponse_ConnectResult_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ConnectService service

type ConnectServiceClient interface {
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
}

type connectServiceClient struct {
	cc *grpc.ClientConn
}

func NewConnectServiceClient(cc *grpc.ClientConn) ConnectServiceClient {
	return &connectServiceClient{cc}
}

func (c *connectServiceClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	out := new(ConnectResponse)
	err := grpc.Invoke(ctx, "/api.ConnectService/connect", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ConnectService service

type ConnectServiceServer interface {
	Connect(context.Context, *ConnectRequest) (*ConnectResponse, error)
}

func RegisterConnectServiceServer(s *grpc.Server, srv ConnectServiceServer) {
	s.RegisterService(&_ConnectService_serviceDesc, srv)
}

func _ConnectService_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectServiceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ConnectService/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectServiceServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConnectService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.ConnectService",
	HandlerType: (*ConnectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "connect",
			Handler:    _ConnectService_Connect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "connect.proto",
}

func init() { proto.RegisterFile("connect.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4f, 0x6b, 0xdc, 0x30,
	0x10, 0xc5, 0xd7, 0x49, 0xbb, 0x21, 0x13, 0xec, 0xba, 0xea, 0x1f, 0xc2, 0x1e, 0x4a, 0x6a, 0x08,
	0x84, 0x1c, 0xf6, 0x90, 0xf6, 0xd2, 0xde, 0x54, 0x49, 0x09, 0x22, 0xb2, 0xb4, 0x48, 0xda, 0x40,
	0x4f, 0xc2, 0x71, 0x45, 0x31, 0x75, 0x6d, 0xd7, 0xd6, 0x16, 0xfa, 0x91, 0xfa, 0x11, 0x7b, 0x2b,
	0xbb, 0x6b, 0x42, 0x0c, 0x39, 0xce, 0x7b, 0x23, 0xbd, 0xe1, 0xfd, 0x20, 0x2e, 0xdb, 0xa6, 0xf1,
	0x65, 0x58, 0x76, 0x7d, 0x1b, 0x5a, 0x74, 0x58, 0x74, 0xd5, 0xe2, 0x24, 0xfc, 0xe9, 0xfc, 0xb0,
	0x57, 0xb2, 0x1e, 0x12, 0xb2, 0x5f, 0xd1, 0xfe, 0xd7, 0xc6, 0x0f, 0x01, 0x7d, 0x82, 0xa4, 0x2c,
	0xea, 0xfa, 0xbe, 0x28, 0x7f, 0xb8, 0x9f, 0xed, 0x37, 0x5f, 0x9f, 0x46, 0x67, 0xd1, 0x45, 0x72,
	0x85, 0x96, 0x45, 0x57, 0x2d, 0xc9, 0x68, 0xe5, 0x5b, 0x47, 0xc7, 0xe5, 0xe3, 0x11, 0x9d, 0x43,
	0x52, 0xb7, 0x65, 0x51, 0xbb, 0xc1, 0x87, 0x50, 0x35, 0xdf, 0x87, 0xd3, 0x83, 0xb3, 0xe8, 0xe2,
	0x58, 0xc7, 0x3b, 0xd5, 0x8c, 0x62, 0xf6, 0x2f, 0x82, 0x17, 0x0f, 0xa1, 0x43, 0xd7, 0x36, 0x83,
	0x47, 0x9f, 0x61, 0xde, 0xfb, 0x61, 0x53, 0x87, 0x31, 0x2d, 0xdb, 0xa7, 0x4d, 0xb7, 0x1e, 0xcd,
	0x9b, 0x3a, 0xe8, 0xf1, 0x45, 0xf6, 0x37, 0x82, 0x78, 0xe2, 0xa0, 0x13, 0x38, 0x32, 0x6b, 0x42,
	0x98, 0x31, 0xe9, 0x0c, 0xbd, 0x81, 0x97, 0x44, 0x49, 0xc9, 0x88, 0xe5, 0x4a, 0xba, 0x6b, 0xcc,
	0x05, 0xa3, 0x69, 0x84, 0xde, 0xc1, 0x62, 0x2d, 0xcd, 0x7a, 0xb5, 0x52, 0xda, 0x32, 0xea, 0x08,
	0x16, 0xe2, 0x0b, 0x26, 0xb7, 0x2e, 0x57, 0x94, 0x89, 0xf4, 0x00, 0x9d, 0xc3, 0x7b, 0x2e, 0xef,
	0xb0, 0xe0, 0xd4, 0x09, 0x45, 0xb0, 0x70, 0x86, 0x59, 0xcb, 0xe5, 0x8d, 0x71, 0x94, 0x19, 0x7e,
	0x23, 0xb1, 0x55, 0x3a, 0x3d, 0xdc, 0xfe, 0x8e, 0x85, 0x66, 0x98, 0x7e, 0x75, 0x63, 0x0a, 0xa3,
	0xe9, 0x33, 0xf4, 0x16, 0x90, 0xb6, 0xdc, 0x71, 0x69, 0x99, 0x96, 0x58, 0x38, 0xa6, 0xb5, 0xd2,
	0xe9, 0xf3, 0xcb, 0x4b, 0x88, 0x27, 0x15, 0xa2, 0x18, 0x8e, 0x79, 0x9e, 0x33, 0xca, 0xb1, 0x65,
	0xe9, 0x0c, 0x01, 0xcc, 0xd9, 0x9d, 0xba, 0xdd, 0x5e, 0x78, 0x75, 0xfd, 0xc0, 0xc6, 0xf8, 0xfe,
	0x77, 0x55, 0x7a, 0xf4, 0x11, 0x8e, 0x46, 0xa0, 0xe8, 0xd5, 0xb4, 0xa0, 0x1d, 0xbb, 0xc5, 0xeb,
	0xa7, 0x5a, 0x5b, 0xcd, 0xee, 0xe7, 0x3b, 0xd8, 0x1f, 0xfe, 0x07, 0x00, 0x00, 0xff, 0xff, 0x33,
	0x45, 0x1a, 0x43, 0x0f, 0x02, 0x00, 0x00,
}
