// Code generated by protoc-gen-go. DO NOT EDIT.
// source: connect.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	connect.proto
	services.proto

It has these top-level messages:
	ConnectRequest
	ConnectResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CallbackModel int32

const (
	CallbackModel_IMMEDIATE CallbackModel = 0
	CallbackModel_EVOKED    CallbackModel = 1
)

var CallbackModel_name = map[int32]string{
	0: "IMMEDIATE",
	1: "EVOKED",
}
var CallbackModel_value = map[string]int32{
	"IMMEDIATE": 0,
	"EVOKED":    1,
}

func (x CallbackModel) String() string {
	return proto.EnumName(CallbackModel_name, int32(x))
}
func (CallbackModel) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ConnectResponse_ConnectError int32

const (
	ConnectResponse_CONNECTION_FAILED                 ConnectResponse_ConnectError = 0
	ConnectResponse_UNSUPPORTED_CALLBACK_MODEL        ConnectResponse_ConnectError = 1
	ConnectResponse_INVALID_LOCAL_SETTINGS_DESIGNATOR ConnectResponse_ConnectError = 2
	ConnectResponse_RTI_INTERNAL_ERROR                ConnectResponse_ConnectError = 3
)

var ConnectResponse_ConnectError_name = map[int32]string{
	0: "CONNECTION_FAILED",
	1: "UNSUPPORTED_CALLBACK_MODEL",
	2: "INVALID_LOCAL_SETTINGS_DESIGNATOR",
	3: "RTI_INTERNAL_ERROR",
}
var ConnectResponse_ConnectError_value = map[string]int32{
	"CONNECTION_FAILED":                 0,
	"UNSUPPORTED_CALLBACK_MODEL":        1,
	"INVALID_LOCAL_SETTINGS_DESIGNATOR": 2,
	"RTI_INTERNAL_ERROR":                3,
}

func (x ConnectResponse_ConnectError) String() string {
	return proto.EnumName(ConnectResponse_ConnectError_name, int32(x))
}
func (ConnectResponse_ConnectError) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

type ConnectRequest struct {
	CallbackModel CallbackModel `protobuf:"varint,1,opt,name=callback_model,json=callbackModel,enum=api.CallbackModel" json:"callback_model,omitempty"`
	LocalSettings string        `protobuf:"bytes,2,opt,name=local_settings,json=localSettings" json:"local_settings,omitempty"`
}

func (m *ConnectRequest) Reset()                    { *m = ConnectRequest{} }
func (m *ConnectRequest) String() string            { return proto.CompactTextString(m) }
func (*ConnectRequest) ProtoMessage()               {}
func (*ConnectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ConnectRequest) GetCallbackModel() CallbackModel {
	if m != nil {
		return m.CallbackModel
	}
	return CallbackModel_IMMEDIATE
}

func (m *ConnectRequest) GetLocalSettings() string {
	if m != nil {
		return m.LocalSettings
	}
	return ""
}

type ConnectResponse struct {
	// Types that are valid to be assigned to OptionalError:
	//	*ConnectResponse_Error
	OptionalError isConnectResponse_OptionalError `protobuf_oneof:"optional_error"`
}

func (m *ConnectResponse) Reset()                    { *m = ConnectResponse{} }
func (m *ConnectResponse) String() string            { return proto.CompactTextString(m) }
func (*ConnectResponse) ProtoMessage()               {}
func (*ConnectResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type isConnectResponse_OptionalError interface {
	isConnectResponse_OptionalError()
}

type ConnectResponse_Error struct {
	Error ConnectResponse_ConnectError `protobuf:"varint,1,opt,name=error,enum=api.ConnectResponse_ConnectError,oneof"`
}

func (*ConnectResponse_Error) isConnectResponse_OptionalError() {}

func (m *ConnectResponse) GetOptionalError() isConnectResponse_OptionalError {
	if m != nil {
		return m.OptionalError
	}
	return nil
}

func (m *ConnectResponse) GetError() ConnectResponse_ConnectError {
	if x, ok := m.GetOptionalError().(*ConnectResponse_Error); ok {
		return x.Error
	}
	return ConnectResponse_CONNECTION_FAILED
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ConnectResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ConnectResponse_OneofMarshaler, _ConnectResponse_OneofUnmarshaler, _ConnectResponse_OneofSizer, []interface{}{
		(*ConnectResponse_Error)(nil),
	}
}

func _ConnectResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ConnectResponse)
	// optional_error
	switch x := m.OptionalError.(type) {
	case *ConnectResponse_Error:
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Error))
	case nil:
	default:
		return fmt.Errorf("ConnectResponse.OptionalError has unexpected type %T", x)
	}
	return nil
}

func _ConnectResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ConnectResponse)
	switch tag {
	case 1: // optional_error.error
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.OptionalError = &ConnectResponse_Error{ConnectResponse_ConnectError(x)}
		return true, err
	default:
		return false, nil
	}
}

func _ConnectResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ConnectResponse)
	// optional_error
	switch x := m.OptionalError.(type) {
	case *ConnectResponse_Error:
		n += proto.SizeVarint(1<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.Error))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*ConnectRequest)(nil), "api.ConnectRequest")
	proto.RegisterType((*ConnectResponse)(nil), "api.ConnectResponse")
	proto.RegisterEnum("api.CallbackModel", CallbackModel_name, CallbackModel_value)
	proto.RegisterEnum("api.ConnectResponse_ConnectError", ConnectResponse_ConnectError_name, ConnectResponse_ConnectError_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ConnectService service

type ConnectServiceClient interface {
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
}

type connectServiceClient struct {
	cc *grpc.ClientConn
}

func NewConnectServiceClient(cc *grpc.ClientConn) ConnectServiceClient {
	return &connectServiceClient{cc}
}

func (c *connectServiceClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	out := new(ConnectResponse)
	err := grpc.Invoke(ctx, "/api.ConnectService/connect", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ConnectService service

type ConnectServiceServer interface {
	Connect(context.Context, *ConnectRequest) (*ConnectResponse, error)
}

func RegisterConnectServiceServer(s *grpc.Server, srv ConnectServiceServer) {
	s.RegisterService(&_ConnectService_serviceDesc, srv)
}

func _ConnectService_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectServiceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ConnectService/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectServiceServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConnectService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.ConnectService",
	HandlerType: (*ConnectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "connect",
			Handler:    _ConnectService_Connect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "connect.proto",
}

func init() { proto.RegisterFile("connect.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x5f, 0xcb, 0xda, 0x30,
	0x18, 0xc5, 0xed, 0xfb, 0xb2, 0x77, 0xf8, 0xb0, 0x76, 0x5d, 0xf6, 0x07, 0xf1, 0x62, 0xa8, 0x20,
	0x88, 0x17, 0x5e, 0xb8, 0xdd, 0x78, 0x19, 0xdb, 0xe8, 0x82, 0x69, 0x22, 0x69, 0xf4, 0x36, 0xd4,
	0x2e, 0x8c, 0xb2, 0xae, 0xe9, 0xda, 0x6e, 0x9f, 0x60, 0x5f, 0x75, 0xdf, 0x63, 0x58, 0x3b, 0x51,
	0x78, 0x2f, 0x9f, 0x73, 0x4e, 0x38, 0xe1, 0xfc, 0xc0, 0x4d, 0x6d, 0x51, 0x98, 0xb4, 0x59, 0x94,
	0x95, 0x6d, 0x2c, 0x7a, 0x4c, 0xca, 0x6c, 0x52, 0x81, 0x17, 0x5c, 0x54, 0x69, 0x7e, 0xfe, 0x32,
	0x75, 0x83, 0x56, 0xe0, 0xa5, 0x49, 0x9e, 0x9f, 0x92, 0xf4, 0xbb, 0xfe, 0x61, 0xbf, 0x9a, 0x7c,
	0xe0, 0x8c, 0x9c, 0x99, 0xb7, 0x44, 0x8b, 0xa4, 0xcc, 0x16, 0x41, 0x67, 0x45, 0x67, 0x47, 0xba,
	0xe9, 0xed, 0x89, 0xa6, 0xe0, 0xe5, 0x36, 0x4d, 0x72, 0x5d, 0x9b, 0xa6, 0xc9, 0x8a, 0x6f, 0xf5,
	0xe0, 0x61, 0xe4, 0xcc, 0xfa, 0xd2, 0x6d, 0xd5, 0xb8, 0x13, 0x27, 0x7f, 0x1d, 0x78, 0x7d, 0x2d,
	0xad, 0x4b, 0x5b, 0xd4, 0x06, 0xad, 0xe0, 0x85, 0xa9, 0x2a, 0x5b, 0x75, 0x65, 0xe3, 0x4b, 0xd9,
	0x7d, 0xe8, 0xff, 0x4d, 0xce, 0xc1, 0x2f, 0x3d, 0x79, 0x79, 0x31, 0xf9, 0xe3, 0xc0, 0xab, 0x5b,
	0x07, 0xbd, 0x87, 0x37, 0x81, 0xe0, 0x9c, 0x04, 0x8a, 0x0a, 0xae, 0x37, 0x98, 0x32, 0x12, 0xfa,
	0x3d, 0xf4, 0x11, 0x86, 0x07, 0x1e, 0x1f, 0xf6, 0x7b, 0x21, 0x15, 0x09, 0x75, 0x80, 0x19, 0x5b,
	0xe3, 0x60, 0xa7, 0x23, 0x11, 0x12, 0xe6, 0x3b, 0x68, 0x0a, 0x63, 0xca, 0x8f, 0x98, 0xd1, 0x50,
	0x33, 0x11, 0x60, 0xa6, 0x63, 0xa2, 0x14, 0xe5, 0xdb, 0x58, 0x87, 0x24, 0xa6, 0x5b, 0x8e, 0x95,
	0x90, 0xfe, 0x03, 0xfa, 0x00, 0x48, 0x2a, 0xaa, 0x29, 0x57, 0x44, 0x72, 0xcc, 0x34, 0x91, 0x52,
	0x48, 0xff, 0x71, 0xed, 0x83, 0x67, 0xcb, 0x26, 0xb3, 0x45, 0x92, 0xeb, 0xf6, 0x63, 0xf3, 0x39,
	0xb8, 0x77, 0x73, 0x21, 0x17, 0xfa, 0x34, 0x8a, 0x48, 0x48, 0xb1, 0x22, 0x7e, 0x0f, 0x01, 0x3c,
	0x91, 0xa3, 0xd8, 0x91, 0xd0, 0x77, 0x96, 0x9b, 0x2b, 0x87, 0xd8, 0x54, 0xbf, 0xb3, 0xd4, 0xa0,
	0xcf, 0xf0, 0xb2, 0xe3, 0x85, 0xde, 0xde, 0xaf, 0xd1, 0x72, 0x1a, 0xbe, 0x7b, 0x6e, 0xa2, 0xd3,
	0x53, 0xcb, 0xf6, 0xd3, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x35, 0xdc, 0x48, 0x93, 0xec, 0x01,
	0x00, 0x00,
}
